---
title: "README"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Springboard Capstone Project

Springboard Capstone Project for The Introduction to Data Science Course

## Problem

The purpose of this project is to analyze taxi fare logs and provide actionable results to the companies. I will create models that predict a trip's fare based on the taxis pickup location, the drop off location, the date and the time of the ride. In addition to that, I am going to compare the yellow taxi and the green taxi companies. The green taxis have limitations in their operations and I want to see how it affects their fares. It would also be interesting to check the fare changes compared to certain events (subway strikes, holidays, new private taxi companies like uber or lyft, weekdays vs weekends)


## Client

The analysis that I am providing would allow Taxi companies to predict their fares

## Data

* [The yellow taxi cabs of New York](https://bigquery.cloud.google.com/table/nyc-tlc:yellow.trips?pli=1)
* [The green taxi cabs of New York 2014](https://bigquery.cloud.google.com/table/nyc-tlc:green.trips_2014?pli=1)
* [The green taxi cabs of New York 2015](https://bigquery.cloud.google.com/table/nyc-tlc:green.trips_2015?pli=1)


## Approach

* Define all interesting variables 
* Collect yellow taxi fares data in Python
* Collect green taxi fares data in Python
* Reproducibly randomly select 50,000 records using the farm fingerprint functionality
* Output csv files of the sample data
* Clean and wrangle the data in R
* Exploratory phase
* Data analysis phase
* Build a regression graph matrix (if needed, go back to the clean & wrangle phase)
* Predict future fare rides


## Deliverables

* Python & R scripts
* Paper
* Presentation